window.APP_CONFIG = {
  VERSION: "2.2.16",
  API_URL: "https://script.google.com/macros/s/AKfycbyC3k5KeD0OqLp9soKwwjkRPBCUOZIfStwPU4QrFYF9FhryqnPs61zVVvTNfT4sXLWPWA/exec",
  VERSION_POLL_MS: 2000,
  FULL_REQUEST_TIMEOUT_MS: 30000,
  VERSION_REQUEST_TIMEOUT_MS: 12000,
  MAX_BATCH_IMAGES: 50,
  IMAGE_REQUEUE_MAX_ROUNDS: 6,
  IMAGE_REQUEUE_BASE_WAIT_MS: 10000,
  IMAGE_ANALYZE_TIMEOUT_MS: 90000,
  DEFAULT_MODE: "normal"
};
